"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
command_timeout = 200
format = "$username$hostname[$directory$git_branch$git_status]($style)$character"

[character]
error_symbol = "[%](bold red)"
success_symbol = "[%](bold)"

[username]
show_always = true
style_user = "green"
style_root = "red"
format = '[$user]($style)'

[hostname]
ssh_only = false        # show even when not on SSH
disabled = false
style = "green"
format = "[@$hostname]($style) "

[directory]
truncation_length = 2
truncation_symbol = "…/"
style = ""
repo_root_style = "blue"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "blue"

[git_status]
format     = '[$all_status]($style)'
style      = "blue"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "" # I always have untracked files, deal with it
modified   = "M "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""
